"""fix string lengths

Revision ID: 87f019df8236
Revises: 
Create Date: 2025-11-13 17:53:15.764866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '87f019df8236'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reportes', sa.Column('nombre', sa.String(length=100), nullable=False))
    op.add_column('reportes', sa.Column('apellido_paterno', sa.String(length=100), nullable=False))
    op.add_column('reportes', sa.Column('apellido_materno', sa.String(length=100), nullable=False))
    op.add_column('reportes', sa.Column('folio', sa.String(length=50), nullable=False))
    op.add_column('reportes', sa.Column('telefono_reportante', sa.String(length=20), nullable=True))
    op.add_column('reportes', sa.Column('direccion', sa.String(length=255), nullable=True))
    op.add_column('reportes', sa.Column('id_categoria', sa.Integer(), nullable=False))
    op.add_column('reportes', sa.Column('id_estado', sa.Integer(), nullable=False))
    op.add_column('reportes', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('reportes', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('reportes', 'descripcion',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=500),
               nullable=True)
    op.alter_column('reportes', 'latitud',
               existing_type=mysql.DECIMAL(precision=10, scale=7),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('reportes', 'longitud',
               existing_type=mysql.DECIMAL(precision=10, scale=7),
               type_=sa.String(length=50),
               nullable=True)
    op.create_index(op.f('ix_reportes_folio'), 'reportes', ['folio'], unique=True)
    op.create_index(op.f('ix_reportes_id_reporte'), 'reportes', ['id_reporte'], unique=False)
    op.create_foreign_key(None, 'reportes', 'categorias', ['id_categoria'], ['id_categoria'])
    op.create_foreign_key(None, 'reportes', 'estados', ['id_estado'], ['id_estado'])
    op.drop_column('reportes', 'tipo_incidente')
    op.drop_column('reportes', 'id_usuario')
    op.drop_column('reportes', 'fecha')
    op.drop_column('reportes', 'estatus')
    op.alter_column('usuarios', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'email',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)
    op.add_column('reportes', sa.Column('estatus', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), server_default=sa.text("'pendiente'"), nullable=False))
    op.add_column('reportes', sa.Column('fecha', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('reportes', sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reportes', sa.Column('tipo_incidente', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
    op.drop_constraint(None, 'reportes', type_='foreignkey')
    op.drop_constraint(None, 'reportes', type_='foreignkey')
    op.drop_index(op.f('ix_reportes_id_reporte'), table_name='reportes')
    op.drop_index(op.f('ix_reportes_folio'), table_name='reportes')
    op.alter_column('reportes', 'longitud',
               existing_type=sa.String(length=50),
               type_=mysql.DECIMAL(precision=10, scale=7),
               nullable=False)
    op.alter_column('reportes', 'latitud',
               existing_type=sa.String(length=50),
               type_=mysql.DECIMAL(precision=10, scale=7),
               nullable=False)
    op.alter_column('reportes', 'descripcion',
               existing_type=sa.String(length=500),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.drop_column('reportes', 'updated_at')
    op.drop_column('reportes', 'created_at')
    op.drop_column('reportes', 'id_estado')
    op.drop_column('reportes', 'id_categoria')
    op.drop_column('reportes', 'direccion')
    op.drop_column('reportes', 'telefono_reportante')
    op.drop_column('reportes', 'folio')
    op.drop_column('reportes', 'apellido_materno')
    op.drop_column('reportes', 'apellido_paterno')
    op.drop_column('reportes', 'nombre')
    # ### end Alembic commands ###
